version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_bai8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"

  nodeapp:
    build: .
    container_name: node_bai8
    ports:
      - "3000:3000"
    depends_on:
      - mysql